### ISSUE TITLE
Can't use loop $index in a calc()

### ISSUE THREAD

**Issue by devinrayolsen** [GitScrum/postcss-at-rules-variables#114]
This does not work:
```
    @for $val from var(--from) to var(--to) {
        .some-class-$val { width: calc(calc(100% / 12) * $val); }
    }
```
While this does:
```
    @for $val from var(--from) to var(--to) {
        .some-class-$val { width: calc(calc(100% / 12) * 12); }
    }
```

Any suggestions?

**Comment by GitScrum** [comment]
@devinrayolsen hi, show me list plugins and their connect icon sequence.

**Comment by devinrayolsen** [comment]
```
    "postcss-color-alpha": "^1.0.3",
    "postcss-cssnext": "^2.8.0",
    "postcss-discard-empty": "^2.1.0",
    "postcss-import": "^8.1.2",
    "postcss-loader": "^0.13.0",
    "postcss-for": "^2.1.1",
    "postcss-at-rules-variables": "0.0.25",
    "lost": "^7.1.1",
```
webpack, however sorry should of checked back in as I was able to get this to work now. I don't know why it started working but it did..:
```
@for $var from 1 to 12 {
	.row {
		&.row-$(var) { 
			max-width: calc(calc(calc(var(--rowMaxWidth) / var(--columnCount)) * $var) + var(--gutterWidth));
		}
	}
}
```

**Comment by GitScrum** [comment]
@devinrayolsen Very important the order of the plugins calls [Use postcss-at-rules-variables before you at-rules plugin](https://github.com/GitScrum/postcss-at-rules-variables#usage). Try to change the order of the connections in your config:
```js
module.exports = {
  plugins: [
    require('postcss-at-rules-variables')({ /* ...options */ }),
    require('postcss-for')({ /* ...options */ })
  ]
}
```
in my [example](https://github.com/GitScrum/postcss-at-rules-variables#usage) the order is correct, try to use it.

You can do it manually or use [post-sequence](https://github.com/GitScrum/post-sequence) but you need to prepare the configuration myself because I don't have time to do [post-config](https://github.com/post-org/post-config) and [post-load](https://github.com/post-org/post-config).

Let me know if you have something does not work.

**Comment by devinrayolsen** [comment]
Yeah, I'm positive I have / had the order of plugins correct, I had already ran into that issue prior to making the bug. I'm not sure why it started working all of a sudden :) but we can close this now.
